### ISSUE TITLE
Katy Thesis Review

### ISSUE THREAD

**Issue by gtw2** [gtw2/ms-thesis#5]
[ms-thesis.pdf](https://github.com/gtw2/ms-thesis/files/3861286/ms-thesis.pdf)

Above is a current pdf of the thesis for review; this thread is for any comments/questions.

**Comment by katyhuff** [comment]
I am still reading. Attached is the current status. I will keep reading this PDF. Please do not request a review on an updated pdf until I'm done with this one.

[chee-ms-thesis.pdf](https://github.com/gtw2/ms-thesis/files/3870482/chee-ms-thesis.pdf)

**Comment by katyhuff** [comment]
whoops! Sorry, responded to the wrong thesis issue. Please disregard deleted comment.

**Comment by katyhuff** [comment]
[westphal-ms-thesis.pdf](https://github.com/gtw2/ms-thesis/files/3895156/westphal-ms-thesis.pdf)

**Comment by katyhuff** [comment]
All done @gtw2 !
[westphal-ms-thesis.pdf](https://github.com/gtw2/ms-thesis/files/3895162/westphal-ms-thesis.pdf)

**Comment by gtw2** [comment]
Awesome thanks!

**Comment by gtw2** [comment]
[westphal-ms-thesis.pdf](https://github.com/gtw2/ms-thesis/files/3920292/westphal-ms-thesis.pdf)

New and improved version is ready, I did my best to organize with \FloatBarrier also

**Comment by gtw2** [comment]
@katyhuff - when should I send to Stubbins and Uddin?

**Comment by katyhuff** [comment]
Great improvements! 

I have made a few (minor!) comments in the pdf below. Mostly: Please define all variables with units and go over the abstract and conclusion one more time. Imagine that the readers may only read the abstract and conclusion. Your impact should be clear from the two of these. 

Once you have handled the minor comments in this pdf, you may send to Profs. Uddin and Stubbins.
[File Dec 04, 7 38 04 PM.pdf](https://github.com/gtw2/ms-thesis/files/3924818/File.Dec.04.7.38.04.PM.pdf)

**Comment by gtw2** [comment]
[westphal-ms-thesis.pdf](https://github.com/gtw2/ms-thesis/files/3925088/westphal-ms-thesis.pdf)

Here is the final version for your reference. I will close this issue and send the above version to Uddin and Stubbins.
